pipeline:
  integration-tests:
    image: ruby:2.4.1
    commands:
      - cd blog
      - bundle install
      - bundle exec rspec
      - git branch
  #security-checks:
    #image: ruby:2.4.1
    #commands:
      