pipeline:
  integration-tests:
    image: ruby:2.4.1
    commands:
      - git fetch origin security-checks
      - git branch
      - bundle install
      - bundle exec rspec
  #security-checks:
    #image: ruby:2.4.1
    #commands:
      